name: Go API CI

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Build and test
        run: |
          docker compose run --rm test go test -coverprofile=coverage.txt -covermode=atomic ./...
          docker cp $(docker ps -aq -f name=remitly-api-test):/app/coverage.txt .

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.txt
