name: Go API CI

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Create coverage directory
        run: mkdir -p coverage

      - name: Build and test
        run: docker compose run --rm test go test -v -coverprofile=/coverage/coverage.txt -covermode=atomic ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: coverage/coverage.txt
